// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the result of creating an invite for a user
 */
export type CreateInviteForUserResult = { "Invite": { url: string, } };