// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the error that can occur when creating an invite for a user
 */
export type CreateInviteForUserError = { "Generic": { message: string, } } | { "ServerNotFound": Record<string, never> } | { "ServerNeedsLoginForInvite": Record<string, never> } | { "UserIsBlacklisted": Record<string, never> } | { "ServerHasNoInvite": Record<string, never> } | { "ServerHasInvalidInvite": Record<string, never> } | { "ServerTypeNotApprovedOrCertified": Record<string, never> } | { "ServerStateNotPublic": Record<string, never> };