// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InfernoplexQuery = { "CreateInvite": { session: string | null, guild_id: string, } } | { "ResolveInvite": { invite_code: string, guild_id: string, } };