// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateInviteForUserResult } from "./CreateInviteForUserResult";

export type InfernoplexResponse = { "CreateInvite": { 
/**
 * Successfully created an invite
 */
result: CreateInviteForUserResult, } } | { "ResolveInvite": Record<string, never> };