// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateInviteForUserError } from "./CreateInviteForUserError";

export type InfernoplexError = { "CreateInvite": { 
/**
 * Successfully created an invite
 */
err: CreateInviteForUserError, 
/**
 * Error message
 */
message: string, } } | { "ResolveInvite": { 
/**
 * The error that occured
 */
message: string, } };